@startuml
'left to right direction
actor Aluno
actor Monitor
actor Professor
actor Administrador

rectangle EduFlow {
  usecase "Fazer Login" as UC1
  usecase "Editar Perfil" as UC2

  ' Casos de Uso do Aluno
  usecase "Agendar Dúvida" as UC_Aluno1
  usecase "Cancelar Reserva" as UC_Aluno2

  ' Casos de Uso do Monitor
  usecase "Cadastrar Agenda" as UC_Monitor1
  usecase "Registrar Atendimento" as UC_Monitor2

  ' Casos de Uso do Professor
  usecase "Vincular Monitor a Disciplina" as UC_Prof1
  usecase "Aprovar Relatórios de Horas" as UC_Prof2
  usecase "Ver Dashboard Analítico" as UC_Prof3

  ' Casos de Uso do Administrador
  usecase "CRUD de Disciplinas" as UC_Admin1
  usecase "Gerenciar Usuários" as UC_Admin2
}

' Atores e seus casos de uso
Aluno -- UC_Aluno1
Aluno -- UC_Aluno2

Monitor -- UC_Monitor1
Monitor -- UC_Monitor2

Professor -- UC_Prof1
Professor -- UC_Prof2
Professor -- UC_Prof3

Administrador -- UC_Admin1
Administrador -- UC_Admin2

' Casos de uso comuns a todos (após login)
(UC_Aluno1) -- UC1 : <<include>>
(UC_Aluno2) -- UC1 : <<include>>
(UC_Monitor1) -- UC1 : <<include>>
(UC_Monitor2) -- UC1 : <<include>>
(UC_Prof1) -- UC1 : <<include>>
(UC_Prof2) -- UC1 : <<include>>
(UC_Prof3) -- UC1 : <<include>>
(UC_Admin1) -- UC1 : <<include>>
(UC_Admin2) -- UC1 : <<include>>
(UC2) -- UC1 : <<include>>

' Generalização de Atores
Administrador --|> Professor
Professor --|> Monitor
Monitor --|> Aluno
Aluno -- UC1
Aluno -- UC2

@enduml
